model:
  name: vit_l
  variant: vit-l
  img_size: 256
  patch_size: 16
  encoder_in_chans: 3
  encoder_embed_dim: 1024
  encoder_depth: 24
  encoder_num_heads: 16
  decoder_embed_dim: 1024
  decoder_depth: 8
  decoder_num_heads: 16
  encoder_pretrained: false
  encoder_pretrained_path: /inspire/hdd/project/wuliqifa/public/dyh/d4rt/checkpoint
  encoder_pretrained_variant: vit-l
  encoder_pretrained_strict: false
  encoder_pretrained_verbose: true
