# Hydra config for PointOdyssey training

defaults:
  - model: vit_b
  - _self_

data_root: /inspire/qb-ilm/project/wuliqifa/public/dyh_data/pointodyssey
split: train

device: cuda
steps: 100000
lr: 1e-4
img_patch_size: 9
batch_size: 2
num_workers: 4
max_grad_norm: 10.0

checkpoint_dir: /inspire/hdd/project/wuliqifa/public/dyh/d4rt/checkpoint
save_every_steps: 1000
save_every_epochs: 1

dataset:
  num_frames: 48
  num_queries: 2048
  no_aug: false
  no_random_stride: false
  val_fraction: 0.05
  val_seed: 42
  val_every_steps: 2000
  val_max_batches: 50

wandb:
  use: false
  project: opend4rt
  entity: null
  name: null
  group: null
  tags: ""
  mode: online
  log_every: 10

tensorboard:
  use: false
  logdir: runs/pointodyssey
