# Hydra config for easydataset training

defaults:
  - model: vit_b
  - _self_

data_dir: /inspire/hdd/project/wuliqifa/public/dyh/d4rt/easydataset

device: cuda
steps: 100000
lr: 1e-4
img_patch_size: 9
batch_size: 2
max_grad_norm: 10.0

checkpoint_dir: checkpoints_easydataset
save_every_steps: 1000

wandb:
  use: false
  project: opend4rt
  entity: null
  name: null
  group: null
  tags: ""
  mode: online
  log_every: 10

tensorboard:
  use: false
  logdir: runs/easydataset
